version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter channel beta
      - run: flutter upgrade
      - run: flutter doctor
      - run: flutter packages get
      - run: flutter test
      - run: flutter build -v apk -t lib/main_dev.dart
      - run: mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/flutterme_dev.apk
      - run: flutter build -v apk -t lib/main_int.dart
      - run: mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/flutterme_int.apk
      - run: flutter build -v apk -t lib/main_prod.dart
      - run: mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/flutterme.apk
