version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter channel beta
      - run: flutter upgrade
      - run: flutter doctor
      - run: flutter packages get
      - run: flutter test
      - run: flutter -v build apk
